server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://192.168.45.161:3306/pass_samples?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: sample1137
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.2

zuul:
  ribbon:
    eager-load:
      enabled: true
      clients: sam-auth,sam-admin
  ignoredServices: '*'
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  ratelimit:
    key-prefix: sam-ratelimite
    enabled: true
    repository: REDIS
    behind-proxy: true
    policies:
      any-admin:
        limit: 100
        quota: 100
        refresh-interval: 3

#eureka:
#  instance:
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 5       #服务刷新时间配置，每隔这个时间会主动心跳一次(默认30秒)
#    lease-expiration-duration-in-seconds: 20   #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除(默认90秒)
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka
#    registry-fetch-interval-seconds: 10         #重新刷新服务地址的时间

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 20   #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除(默认90秒)
    lease-renewal-interval-in-seconds: 5       #服务刷新时间配置，每隔这个时间会主动心跳一次(默认30秒)
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 10  #重新刷新服务地址的时间

security:
  encode:
    key: '1234567887654321' #必须16位
  auth:
    server: http://localhost:9002
  validate:
    code: true # 验证码开关
    preview: false
  sessions: stateless
  oauth2:
    client:
      client-id: pig
      client-secret: pig
      scope: server
    resource:
      loadBalanced: true
      token-info-uri: ${security.auth.server}/oauth/check-token
      service-id: any-gateway
      jwt:
        key-uri: ${security.auth.server}/oauth/token_key #解析jwt令牌所需要密钥的地址

ignore:
  urls:
    - /mobile/**
    - /auth/**
    - /oauth/**
    - /admin/code/*
    - /admin/smsCode/*
    - /admin/user/info
    - /admin/userMenu
    - /swagger-resources/**
    - /swagger-ui.html
    - /*/v2/api-docs
    - /swagger/api-docs
    - /webjars/**
  clients:
    - app
